In [2]:
import numpy as np

In [6]:
array_a = np.array([1,2,3])
array_a

array([1, 2, 3])

In [8]:
array_b = np.array([[1,2,3], [4,5,6]])
array_b

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
import pandas as pd

In [11]:
pd.__version__

'1.5.3'

In [12]:
products = ['A', 'B', 'C', 'D']
products

['A', 'B', 'C', 'D']

In [13]:
type(products)

list

In [14]:
product_categories = pd.Series(products)

In [15]:
product_categories

0    A
1    B
2    C
3    D
dtype: object

In [16]:
type(product_categories)

pandas.core.series.Series

In [17]:
daily_rates_dollars =  pd.Series([40, 45, 50, 60])

In [18]:
daily_rates_dollars

0    40
1    45
2    50
3    60
dtype: int64

In [19]:
import numpy as np


In [20]:
array_a = np.array([10,20,30,40,50])

In [21]:
array_a

array([10, 20, 30, 40, 50])

In [22]:
series_a = pd.Series(array_a)

In [23]:
series_a

0    10
1    20
2    30
3    40
4    50
dtype: int32

In [24]:
prices_per_category = {'Product A': 22250, 'Product B': 16600, 'Product C': 15600}

In [25]:
prices_per_category

{'Product A': 22250, 'Product B': 16600, 'Product C': 15600}

In [27]:
prices_per_category = pd.Series(prices_per_category)
prices_per_category

Product A    22250
Product B    16600
Product C    15600
dtype: int64

In [28]:
series_b = pd.Series([10,20,30,40,50], index = [1,2,3,4,5])

In [30]:
series_b[1]

10

In [35]:
start_date_deposits = pd.Series({
    '7/4/2014': 2000,
    '1/2/2015': 2000,
    '12/8/2012': 1000,
    '2/20/2015': 2000,
    '10/28/2013': 2000,
    '4/19/2015': 2000,
    '7/4/2016': 2000,
    '4/24/2014': 2000,
    '9/3/2015': 4000,
    '7/25/2016': 2000,
    '5/1/2014': 2000,
    '3/29/2013': 2000,
    '10/3/2014': 2000,
    '9/18/2015': 2500
})

In [37]:
start_date_deposits.sum()

29500

In [38]:
start_date_deposits.min()

1000

In [39]:
start_date_deposits.max()

4000

In [40]:
start_date_deposits.idxmax()

'9/3/2015'

In [41]:
start_date_deposits.idxmin()

'12/8/2012'

In [42]:
start_date_deposits.head()

7/4/2014      2000
1/2/2015      2000
12/8/2012     1000
2/20/2015     2000
10/28/2013    2000
dtype: int64

In [43]:
start_date_deposits.tail()

7/25/2016    2000
5/1/2014     2000
3/29/2013    2000
10/3/2014    2000
9/18/2015    2500
dtype: int64

["DATA FRAME A PARTIR DE DISCIONÁRIO"]

In [47]:
data = {'ProdutName':['Product A', 'Product B', 'Product C'], 'ProductPrice':[22250,16600,12500]}
df = pd.DataFrame(data)
df
df2 = pd.DataFrame(data, index = ['A', 'B', 'C'])
df2

ProdutName  ProductPrice
A  Product A         22250
B  Product B         16600
C  Product C         12500

In [49]:
data = {'ProdutName':['Product A', 'Product B', 'Product C'], 'ProductPrice':[22250,16600,12500]}
df = pd.DataFrame(data)
df
products_IDs =['A', 'B', 'C']
df2 = pd.DataFrame(data, index = products_IDs)
df2

ProdutName  ProductPrice
A  Product A         22250
B  Product B         16600
C  Product C         12500

In [50]:
df = pd.DataFrame(data=[['Product A', 22250], ['Product B', 16600], ['Product C', 12500]], 
                 columns = ['ProductName', 'ProductPrice'],
                 index = ['A', 'B', 'C'])
df

ProductName  ProductPrice
A   Product A         22250
B   Product B         16600
C   Product C         12500

In [51]:
df.shape

(3, 2)