<center><h3><b>BASIC COMMANDS - NUMPY<b/><h3/><center/>

In [7]:
#Importando a biblioteca

import numpy as np

In [8]:
#Criando e visualizando array a partir da função array

array1 = np.array([18,21,32,44,56,64,73,85,99])
print(array1)

[18 21 32 44 56 64 73 85 99]


In [9]:
#Verificando o formato/número de dimensões do array

array1.shape

(9,)

In [13]:
#Criando lista de índices e visualizando elementos

indices = [1,2,5,6]
array1[indices]

array([21, 32, 64, 73])

In [18]:
#Verificando os pares

mascara = (array1 % 2 == 0)
array1[mascara]

array([18, 32, 44, 56, 64])

In [19]:
#Visualizar a soma acumulada dos elementos

array1.cumsum()

array([ 18,  39,  71, 115, 171, 235, 308, 393, 492])

In [20]:
#Visualizar o produto acumulado dos elementos

array1.cumprod()

array([        18,        378,      12096,     532224,   29804544,
       1907490816, 1807876096, -949354496,  503185408])

In [23]:
#Criar progressão aritmética com função arange

array2 = np.arange(0,40,4)
array2

array([ 0,  4,  8, 12, 16, 20, 24, 28, 32, 36])

In [24]:
#Criar array preenchido com zeros

array3 = np.zeros(10)
array3

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [26]:
#Criar matriz identidade 

array4 = np.eye(4)
array4

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [33]:
#Criar matriz com diagonal com valores diferentes de zero

array5 = np.diag(np.array([1,3,5,7]))
array5

array([[1, 0, 0, 0],
       [0, 3, 0, 0],
       [0, 0, 5, 0],
       [0, 0, 0, 7]])

In [34]:
#Criar array com elementos espaçados no mesmo intervalo

print(np.linspace(0,10))

[ 0.          0.20408163  0.40816327  0.6122449   0.81632653  1.02040816
  1.2244898   1.42857143  1.63265306  1.83673469  2.04081633  2.24489796
  2.44897959  2.65306122  2.85714286  3.06122449  3.26530612  3.46938776
  3.67346939  3.87755102  4.08163265  4.28571429  4.48979592  4.69387755
  4.89795918  5.10204082  5.30612245  5.51020408  5.71428571  5.91836735
  6.12244898  6.32653061  6.53061224  6.73469388  6.93877551  7.14285714
  7.34693878  7.55102041  7.75510204  7.95918367  8.16326531  8.36734694
  8.57142857  8.7755102   8.97959184  9.18367347  9.3877551   9.59183673
  9.79591837 10.        ]


In [35]:
#Criar array com elementos espaçados num mesmo intervalo em escala logarítmica

print(np.logspace(0,10))

[1.00000000e+00 1.59985872e+00 2.55954792e+00 4.09491506e+00
 6.55128557e+00 1.04811313e+01 1.67683294e+01 2.68269580e+01
 4.29193426e+01 6.86648845e+01 1.09854114e+02 1.75751062e+02
 2.81176870e+02 4.49843267e+02 7.19685673e+02 1.15139540e+03
 1.84206997e+03 2.94705170e+03 4.71486636e+03 7.54312006e+03
 1.20679264e+04 1.93069773e+04 3.08884360e+04 4.94171336e+04
 7.90604321e+04 1.26485522e+05 2.02358965e+05 3.23745754e+05
 5.17947468e+05 8.28642773e+05 1.32571137e+06 2.12095089e+06
 3.39322177e+06 5.42867544e+06 8.68511374e+06 1.38949549e+07
 2.22299648e+07 3.55648031e+07 5.68986603e+07 9.10298178e+07
 1.45634848e+08 2.32995181e+08 3.72759372e+08 5.96362332e+08
 9.54095476e+08 1.52641797e+09 2.44205309e+09 3.90693994e+09
 6.25055193e+09 1.00000000e+10]


In [36]:
#Criando matriz

matriz = np.array([[1,2,3],[4,5,6]])
matriz

array([[1, 2, 3],
       [4, 5, 6]])

In [39]:
#Criando matriz 2x3 preenchida por 1

matriz23 = np.ones((2,3))
matriz23

array([[1., 1., 1.],
       [1., 1., 1.]])

In [40]:
#Criando matriz a partir de lista de listas

lista = [[13,81,22], [0,34,59], [22,85,63]]
matriz33 = np.matrix(lista)
matriz33

matrix([[13, 81, 22],
        [ 0, 34, 59],
        [22, 85, 63]])

In [44]:
#Visualizar os 2 primeiras linhas da coluna 3

matriz33[0:2,2]

matrix([[22],
        [59]])

In [47]:
#Forçando float como saída do array

x = np.array([1,2,7,9,6,3], dtype = np.float64)
print(x)

[1. 2. 7. 9. 6. 3.]


In [48]:
#Vereificando o espaço em bytes ocupado na memória por cada elemento

x.itemsize

8